import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";

// Simulated API fetch
const fetchIssueDetails = async (id: string) => {
  // Replace with real API call
  return {
    header: {
      id,
      issueNo: "ISS-3001",
      issueDate: "2025-08-15",
      issueDepartment: "General Ward",
      requisitionId: "REQ-5001",
      generatedBy: "Jane Smith",
    },
    items: [
      {
        slNo: 1,
        itemName: "Paracetamol",
        batchNo: "B123",
        expDate: "2026-05-01",
        quantity: 200,
        amount: 240,
      },
      {
        slNo: 2,
        itemName: "Amoxicillin",
        batchNo: "B124",
        expDate: "2026-08-15",
        quantity: 100,
        amount: 170,
      },
    ],
  };
};

const ViewIssueDetails = () => {
  const { id } = useParams<{ id: string }>();
  const [issue, setIssue] = useState<any>(null);

  useEffect(() => {
    if (id) {
      fetchIssueDetails(id).then((data) => setIssue(data));
    }
  }, [id]);

  if (!issue) return <p>Loading issue details...</p>;

  const { header, items } = issue;

  return (
    <div className="pl-2">
      <div>
        <h2 className="text-2xl font-bold text-[#035d67] mb-6 bg-[var(--base-color)] p-2">
          VIEW ISSUE DETAILS
        </h2>
      </div>

      {/* HEADER */}
      <div className="mt-4 bg-gray-100 p-3 rounded">
        <div className="grid grid-cols-3 gap-2">
            
          <p>
            <strong><span className="text-red-600 font-semibold mr-2">☮</span>Issue No.:</strong> {header.issueNo}
          </p>
          <p>
            <strong><span className="text-red-600 font-semibold mr-2">☮</span>Issue Date:</strong> {header.issueDate}
          </p>
          <p>
            <strong><span className="text-red-600 font-semibold mr-2">☮</span>Issue Department:</strong> {header.issueDepartment}
          </p>
          <p>
            <strong><span className="text-red-600 font-semibold mr-2">☮</span>Requisition ID:</strong> {header.requisitionId}
          </p>
          <p>
            <strong><span className="text-red-600 font-semibold mr-2">☮</span>Generated By:</strong> {header.generatedBy}
          </p>
        </div>
      </div>

      {/* ITEMS TABLE */}
      <div className="mt-6 overflow-auto border border-gray-300 rounded">
        <table className="min-w-[800px] w-full border-collapse text-sm">
          <thead className="bg-[#2fe2fe] text-gray-900 text-left">
            <tr>
              {[
                "Sl. No.",
                "Item Name",
                "Batch No.",
                "Exp. Date",
                "Quantity",
                "Amount",
              ].map((col, i) => (
                <th key={i} className="border border-gray-300 px-2 py-1">
                  {col}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {items.map((row: any, index: number) => (
              <tr key={index} className="bg-white">
                {[
                  "slNo",
                  "itemName",
                  "batchNo",
                  "expDate",
                  "quantity",
                  "amount",
                ].map((key, i) => (
                  <td
                    key={i}
                    className="border border-gray-300 px-2 py-1"
                  >
                    {row[key]}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default ViewIssueDetails;
